version: "3.9"

networks:
  mynet:
    name: mynet
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

services:
  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - mysql_db
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - mynet
    ports:
      - 8088:80
    environment:
      PMA_HOST: 10.5.0.10
      MYSQL_ROOT_PASSWORD: "SAME PASSWORD AS DATABASE ROOT"
